language: rust

rust: stable

cache: cargo

install:
  - cargo install ripgrep || true

before_script:
  - git clone https://github.com/rust-lang/rust.git

script:
  - travis_wait ./ci/script.sh

after_success:
  - cp rust/stable_feature*.txt rust/unstable_feature*.txt .
  - cat stable_feature_latest_commit.txt | cut -f3 > stable_feature_latest_commit_time.txt
  - { echo "Feature Name\tSince\tFirst Commit Timestamp\tLatest Commit Timestamp"; paste stable_feature_first_commit.txt stable_feature_latest_commit_time.txt | sort -V -k2,2 -k3,3 -k4,4; } | column -t -s $'\t' -n
  - cat unstable_feature_latest_commit.txt | cut -f3 > unstable_feature_latest_commit_time.txt
  - { echo "Feature Name\tIssue #\tFirst Commit Timestamp\tLatest Commit Timestamp"; paste unstable_feature_first_commit.txt unstable_feature_latest_commit_time.txt | sort -k3,3 -k4,4; } | column -t -s $'\t' -n

notifications:
  email:
    on_success: never
