language: rust

rust: stable

cache: cargo

install:
  - cargo install ripgrep

before_script:
  - git clone https://github.com/rust-lang/rust.git

script:
  - travis_wait ./ci/script.sh

after_success:
  - cat stable_feature_latest_commit.txt | cut -f3 > stable_feature_latest_commit_time.txt
  - paste stable_feature_latest_commit.txt stable_feature_latest_commit_time.txt | sort -V -k2,2 -k3,3 -k4,4 | column -t -s $'\t' -n
  - cat unstable_feature_latest_commit.txt | cut -f3 > unstable_feature_latest_commit_time.txt
  - paste unstable_feature_latest_commit.txt unstable_feature_latest_commit_time.txt | sort -k3,3 -k4,4 | column -t -s $'\t' -n

notifications:
  email:
    on_success: never
